### ISSUE TITLE
DeepQNetwork has no attribute "fc1"

### ISSUE THREAD

**Issue by elyesmanai** [uvipen/Tetris-deep-Q-learning-pytorch#1]
hey there buddy, I get this error while trying to run test.py. 
AttributeError: 'DeepQNetwork' object has no attribute 'fc1'

Checking your class, there's an fc1 attribute but you're using it as a function? 

![image](https://user-images.githubusercontent.com/21007166/77867874-5e5bd380-7239-11ea-8732-cc56643554c5.png)

**Comment by vietnh1009** [comment]
Could you pull again and run. At the beginning the name for these layers are not fc1, fc2, fc3 but conv1, conv2, conv3. I only realize that the name should be fc instead of conv after training phase done.

**Comment by elyesmanai** [comment]
'ReLU' object has no attribute 'threshold'

**Comment by vietnh1009** [comment]
I guess you should upgrade your pytorch.
